### PR TITLE
config pom.xml to deploy to maven central

### PR DESCRIPTION
**Pull request by nidi3**

### CODE REVIEW

**Comment by blackears** [comment]
Thanks for the patch.  Would you have any advice on how I'd actually deploy this to central?  I've not had much luck with deploying on Maven in the past.

**Comment by nidi3** [comment]
As described in https://github.com/blackears/svgSalamander/issues/9, you must generate and publish a pgp keypair https://central.sonatype.org/pages/working-with-pgp-signatures.html, then simply execute `mvn deploy -Pdeploy`

**Comment by blackears** [comment]
I tried deploying with your updated pom, but am getting the below error message when I try to deploy.  Would you know how I could fix this?

`[ERROR] Failed to execute goal org.sonatype.plugins:nexus-staging-maven-plugin:1.6.8:deploy (injected-nexus-deploy) on project svgSalamander: Execution injected-nexus-deploy of goal org.sonatype.plugins:nexus-staging-maven-plugin:1.6.8:deploy failed: Server credentials with ID "ossrh" not found! -> [Help 1]`

**Comment by nidi3** [comment]
I forgot, you have to add your account for https://issues.sonatype.org to your ~/.m2/settings.xml:
```
 <servers>
        <server>
            <id>ossrh</id>
            <username>...</username>
            <password>...</password>
        </server>
```

**Comment by blackears** [comment]
I tried again.  I got further, but encountered another error:

```
[ERROR] Failed to execute goal org.sonatype.plugins:nexus-staging-maven-plugin:1.6.8:deploy (injected-nexus-deploy) on project svgSalamander: Execution injected-nexus-deploy of goal org.sonatype.plugins:nexus-staging-maven-plugin:1.6.8:deploy failed: 403 - Forbidden -> [Help 1]
```

**Comment by nidi3** [comment]
That's strange. Is there any hint as to what staging rules failed? Maybe when you try running it with -X flag, there's even more information.

**Comment by nidi3** [comment]
I see your try on https://oss.sonatype.org/#stagingRepositories with id `central_bundles-16894`.
Maybe you can try releasing from there and hope for a better error message.

**Comment by blackears** [comment]
Trying to release using Sonatype's web interface results in the same generic error message:

Release failed

Nexus returned an error: ERROR 403: Forbidden

**Comment by nidi3** [comment]
Just to be sure, do you have the rights for com.kitfox?
On the same sonatype page, when you select "Central Statistics" from the left hand menu, then in the "project" dropdown, do you see com.kitfox as an option?

**Comment by blackears** [comment]
The project dropdown has no entries in it.

**Comment by nidi3** [comment]
Sometimes it takes some time till it's ready. Did you request access to com.kitfox via sonatype's jira?

**Comment by blackears** [comment]
Not sure.  If I have, it was years ago when I first set up the account.

**Comment by blackears** [comment]
How would I go about requesting access?

**Comment by nidi3** [comment]
Here is the complete guide: https://central.sonatype.org/pages/ossrh-guide.html
And what my own jira ticket looked like: https://issues.sonatype.org/browse/OSSRH-9801

**Pull request merged**
